### ISSUE TITLE
Connect with Raspberry Pi

### ISSUE THREAD

**Issue by lombardi-zz** [docbender/Onkyo-RI#1]
Hello. Can you give a example how to connect RI to a Raspberry 2 ?

**Comment by docbender** [comment]
Hi,

I dont know Pi exactly, but I think that it uses 3,3V IO logic and Onkyo 
needs 5V logic. So to direct connection it will need to use some GPIO pin 
maybe with some level conversion. Never tried.

I use it in this way:

                  USB/serial                          2wire TTL connection

     PC <==========> Arduino =================> Onkyo
- Arduino is man-in-the-middle. Receives data from PC and it uses my 
  Onkyo-RI library and sends commands to Onkyo
- Arduino with PC is connected through USB or serial port
- on PC I have installed openHAB software

Hope it help a little

Vita

---------- Původní zpráva ----------
Od: lombardi-zz notifications@github.com
Komu: docbender/Onkyo-RI Onkyo-RI@noreply.github.com
Datum: 7. 4. 2016 19:39:26
Předmět: [docbender/Onkyo-RI] Connect with Raspberry Pi (#1)

"

Hello. Can you give a example how to connect RI to a Raspberry 2 ? 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
(https://github.com/docbender/Onkyo-RI/issues/1) 

# "

**Comment by lombardi-zz** [comment]
Thank You. It´s work with 3,3V without Problem. I compiled the code with WiringPi header.

**Comment by gingerbeardman** [comment]
Can you please share Pi binary? @lombardi-zz

**Comment by S1N4X** [comment]
@gingerbeardman please see : https://github.com/sinaxin/Onkyo-Pi
